WebApplication1/Controllers/CurrencyController.cs
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class CurrencyController : Controller
    {
        private readonly ICurrencyModel _model;

        public CurrencyController(ICurrencyModel model)
        {
            _model = model;
        }

        [HttpGet]
        public ActionResult Index()
        {
            ViewBag.CurrencyList = _model.Get();
            return View();
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Show(Guid id)
        {
            ViewBag.Currency = _model.Get(id);
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Add(string nameFrom, string nameTo, string codeFrom, string codeTo)
        {
            if (string.IsNullOrWhiteSpace(nameFrom))
                ModelState.AddModelError("nameFrom", "Поле имя базовой валюты обязательно для заполнения");

            if (string.IsNullOrWhiteSpace(nameTo))
                ModelState.AddModelError("nameTo", "Поле имя валюты назначения обязательно для заполнения");

            if (string.IsNullOrWhiteSpace(codeFrom))
                ModelState.AddModelError("codeFrom", "Поле код базовой валюты обязательно для заполнения");

            if (string.IsNullOrWhiteSpace(codeTo))
                ModelState.AddModelError("codeTo", "Поле код валюты назначения обязательно для заполнения");

            if (!ModelState.IsValid)
                return View();

            await _model.Create(nameFrom, nameTo, codeFrom, codeTo);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Update(Guid id)
        {
            ViewBag.Currency = _model.Get(id);
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Update(Guid id, string nameFrom, string nameTo, string codeFrom, string codeTo)
        {
            if (string.IsNullOrWhiteSpace(nameFrom))
                ModelState.AddModelError("nameFrom", "Поле имя базовой валюты обязательно для заполнения");

            if (string.IsNullOrWhiteSpace(nameTo))
                ModelState.AddModelError("nameTo", "Поле имя валюты назначения обязательно для заполнения");

            if (string.IsNullOrWhiteSpace(codeFrom))
                ModelState.AddModelError("codeFrom", "Поле код базовой валюты обязательно для заполнения");

            if (string.IsNullOrWhiteSpace(codeTo))
                ModelState.AddModelError("codeTo", "Поле код валюты назначения обязательно для заполнения");

            if (!ModelState.IsValid)
                return View();

            await _model.Update(id, nameFrom, nameTo, codeFrom, codeTo);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<ActionResult> Delete(Guid id)
        {
            await _model.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

WebApplication1/Controllers/RateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class RateController : Controller
    {
        private readonly ICurrencyModel _currencyModel;


        public RateController(ICurrencyModel currencyModel)
        {
            _currencyModel = currencyModel;
        }

        [System.Web.Http.HttpGet]
        public ActionResult Index()
        {
            var currencyList = new SelectList(_currencyModel.Get().Select(c => c.CodeFrom + c.CodeTo));
            ViewBag.CurrencyList = currencyList;
            return View();
        }
    }
}

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/datetimepicker")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Курсатор", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Домой", "Index", "Home")</li>
                    @if (User.Identity.Name == "Admin1@Admin.ru")
                    {
                        <li>@Html.ActionLink("Настройка валюты", "Index", "Currency")</li>
                    }
                    <li>@Html.ActionLink("График валют", "Index", "Rate")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Test Site</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/graph")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>